### ISSUE TITLE
Support for parsing complex unit types

### ISSUE THREAD

**Issue by eneimi** [gdl-lang/gdl2#3]
Currently unable to parse relative GFR with unit: `ml/min/1.73m2`. The parser truncates every character after `ml/min/1`.

**Comment by rongchen** [comment]
The correct unit string should be "mL/min/{1.73_m2}" instead. 
See the discussion here, http://unitsofmeasure.org/trac/ticket/98
and sample fhir observation, https://www.hl7.org/fhir/observation-example-f205-egfr.json

**Comment by rongchen** [comment]
Both "ml/min/1.73m2" and "mL/min/{1.73_m2}" are supported now.
